version: '3'
services:
  app:
    build:
      context: app
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
  api:
    build:
      context: api
    tty: true
    ports:
      - 8081:8080
    volumes:
      - ./api:/app
